// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/tot_list.proto

package com.insight.demo.serialize.model.msgpack;

import org.msgpack.annotation.Message;


@Message
public class DataCacheMessage {
    public boolean compact;
    public int schema;

}
